PipelineSecrets:
  DockerConfig: '{"auths":{"cgldev.azurecr.io":{"auth":"Y2dsZGV2OkVFT3FmbE9CV29QaDhRWjRaU2s5ZitramFxVlhmNldu"}}}'
cleanup:
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --cleanup
controllerbuild:
  enabled: true
controllerworkflow:
  enabled: false
dockerRegistry: cgldev.azurecr.io
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --v
  - 4
  config:
    domain: 13.88.246.150.nip.io
    exposer: Ingress
    http: "true"
jenkins:
  Servers:
    Global:
      EnvVars:
        TILLER_NAMESPACE: kube-system
  enabled: false
prow: {}
